# Generated by Django 3.2 on 2024-05-14 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('zone', models.CharField(max_length=255, null=True)),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('UPCOMING', 'Upcoming'), ('ENDED', 'Ended')], default='UPCOMING', max_length=50)),
                ('is_running', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('audio_file_path', models.CharField(max_length=255, null=True)),
                ('audio_text', models.TextField(null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_app.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='songs')),
                ('stream_chunks', models.ManyToManyField(related_name='songs', to='stream_app.StreamChunk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
