# Generated by Django 3.2 on 2024-05-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='stream_chunks',
        ),
        migrations.AddField(
            model_name='streamchunk',
            name='songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_app.song'),
        ),
    ]
