# Generated by Django 3.2 on 2024-05-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0002_auto_20240515_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamchunk',
            old_name='songs',
            new_name='song',
        ),
    ]
