# Generated by Django 3.2 on 2024-05-15 12:16

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(username='admin', email='admin@example.com', password='12345')

class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0004_auto_20240515_0741'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
